return {
	["tag_uncommon"] = 1,
	["tag_rare"] = 1,
	["tag_negative"] = 2,
	["tag_foil"] = 1,
	["tag_holo"] = 1,
	["tag_polychrome"] = 1,
	["tag_investment"] = 1,
	["tag_voucher"] = 2,
	["tag_boss"] = 2,
	["tag_standard"] = 2,
	["tag_charm"] = 1,
	["tag_meteor"] = 2,
	["tag_buffoon"] = 2,
	["tag_handy"] = 2,
	["tag_garbage"] = 2,
	["tag_ethereal"] = 2,
	["tag_coupon"] = 1,
	["tag_double"] = 1,
	["tag_juggle"] = 2,
	["tag_d_six"] = 2,
	["tag_top_up"] = 2,
	["tag_skip"] = 1,
	["tag_orbital"] = 2,
	["tag_economy"] = 2,
}